# Generated by Django 4.1 on 2022-08-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descreption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
