# Generated by Django 4.1 on 2022-09-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_products_delete_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/'),
        ),
    ]
